// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALI3ld7_q2-iBsP0-WdWIUTqHQWpXIrxI',
    appId: '1:930183812328:web:99b89c84cfc5510398655d',
    messagingSenderId: '930183812328',
    projectId: 'authtcc',
    authDomain: 'authtcc.firebaseapp.com',
    storageBucket: 'authtcc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8epzEzqSiQjdcHK3tqQ-Of5-qPri7I6U',
    appId: '1:930183812328:android:5ab18a511cc3b41298655d',
    messagingSenderId: '930183812328',
    projectId: 'authtcc',
    storageBucket: 'authtcc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChmoY9ZT0Hwifky2NKL3BBoY9DsgLcS70',
    appId: '1:930183812328:ios:28015078045ba14198655d',
    messagingSenderId: '930183812328',
    projectId: 'authtcc',
    storageBucket: 'authtcc.appspot.com',
    iosBundleId: 'com.example.dinoDiary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChmoY9ZT0Hwifky2NKL3BBoY9DsgLcS70',
    appId: '1:930183812328:ios:b26bc2c2e0ef01a598655d',
    messagingSenderId: '930183812328',
    projectId: 'authtcc',
    storageBucket: 'authtcc.appspot.com',
    iosBundleId: 'com.example.dinoDiary.RunnerTests',
  );
}
